{
 "title": "Prac 3 Localisation",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Position (x,y)",
   "type": "geomap",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket:\"prac3\")\n  |> range(start:-5m)\n  |> filter(fn:(r) => r._measurement == \"position\" and r.method == \"kalman\")\n  |> filter(fn:(r) => r._field == \"x\" or r._field == \"y\")\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_field\"], valueColumn:\"_value\")\n  |> map(fn:(r) => ({ r with latitude: r.y, longitude: r.x }))"
    },
    {
     "query": "from(bucket:\"prac3\")\n  |> range(start:-5m)\n  |> filter(fn:(r) => r._measurement == \"ibeacon_positions\")\n  |> filter(fn:(r) => r._field == \"x\" or r._field == \"y\")\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_field\"], valueColumn:\"_value\")\n  |> map(fn:(r) => ({ r with latitude: r.y, longitude: r.x }))"
    }
   ]
  },
  {
   "title": "Average Velocity (m/s)",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"math\"\n\nfrom(bucket:\"prac3\")\n  |> range(start:-30s)\n  |> filter(fn:(r)=> r._measurement==\"position\" and r.method==\"kalman\" and (r._field==\"vx\" or r._field==\"vy\"))\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_field\"], valueColumn:\"_value\")\n  |> filter(fn:(r)=> exists r.vx and exists r.vy)\n  |> map(fn:(r)=> ({ _time: r._time, _value: math.sqrt(x: float(v: r.vx*r.vx + r.vy*r.vy)) }))"
    }
   ]
  },
  {
   "title": "Distance Travelled (m)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"math\"\n\nfrom(bucket:\"prac3\")\n  |> range(start:-5m)\n  |> filter(fn:(r)=> r._measurement==\"position\" and r.method==\"kalman\" and (r._field==\"x\" or r._field==\"y\"))\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_field\"], valueColumn:\"_value\")\n  |> filter(fn:(r)=> exists r.x and exists r.y)\n  |> window(every: 1s)\n  |> difference(nonNegative:true, columns:[\"x\",\"y\"])\n  |> filter(fn:(r)=> exists r.x and exists r.y)\n  |> map(fn:(r)=> ({ _time: r._time, _value: math.sqrt(x: float(v: r.x*r.x + r.y*r.y)) }))\n  |> cumulativeSum()"
    }
   ]
  },
  {
   "title": "RSSI Values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "query": "from(bucket:\"prac3\")\n  |> range(start:-5m)\n  |> filter(fn:(r) => r._measurement == \"position\" and r.method == \"multilat\" and r._field == \"rssi\")\n  |> group(columns: [\"ibeacon\"])"
    }
   ]
  },
  {
   "title": "Ultrasonic Range",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "query": "from(bucket:\"prac3\")\n  |> range(start:-5m)\n  |> filter(fn:(r) => r._measurement == \"position\" and r.method == \"ultrasonic\" and r._field == \"us_range\")\n  |> group(columns: [\"node\"])"
    }
   ]
  }
 ]
}